### ISSUE TITLE
busqueda de lotres

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#10]
En granja, cuando se guarda el lote, aparece la fecha  de 2015!!! El servidor está con la fecha actualizada??? 
Esto lo hemnos visto al buscar

**Comment by jesusMadrazoCabrera** [comment]
Revisar las busquedas de lotes dentro de granja.
Crearse un lote y ver si lo entontramos.


![image](https://user-images.githubusercontent.com/44262150/47203213-d9039c80-d37f-11e8-8ca9-53ad1eae9e5e.png)

**Comment by SergioCarrilloEspejo** [comment]
Después de hablar con Angel en las búsquedas desaparece el 2015 y el nombre de la facility,
Ya que ese campo no lo recupera de IFT, solo muestra el nombre del lote
