### ISSUE TITLE
En la pantalla anterior, que los campos aparezcan alineado

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#11]
En la lista de búsqueda de granja. Eliminar los datos estáticos

**Comment by jesusMadrazoCabrera** [comment]
Relacionada con la #10 que los datos que aparezcan, aparezcan alineados, o si no devuelve mas datos, desaparezcan.

**Comment by amoranviewnext** [comment]
Corregido. Se han alineado los campos en la búsqueda.
