### ISSUE TITLE
Al buscar un lote no recupera los datos del lote seleccionado

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#12]
Al buscar un lote no recupera los datos del lote seleccionado.  Might be the same than 1. - duplicated -

**Comment by jesusMadrazoCabrera** [comment]
Reasignacion

**Comment by jesusMadrazoCabrera** [comment]
Faltan datos de los combos con informacion con "."

**Comment by jfmarquez** [comment]
Probado en entorno. Funciona OK
