### ISSUE TITLE
Búsqueda en despiece

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#19]
En   despiece la busqueda muestra los lotes de matadero

**Comment by jesusMadrazoCabrera** [comment]
Revisar la busqueda en la pantalla y ver si se le esta enviando algun parametro de forma incorrecta.

**Comment by SergioCarrilloEspejo** [comment]
Despiece estaba integrao en matadero, no era una facility dentro de ift con lo cual aparecen cosas de matardero
