### ISSUE TITLE
Planta de procesado en preparacion de pedido

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#20]
En Prep.   Order, o sobra la info de sala procesado o el comportamiento deberia de ser        que cuando seleccionamos un lote de despiece, se rellene el campo Planta   Procesado con la      información que hemos puesto en el paso anterior (despiece). (Jesus)

**Comment by jesusMadrazoCabrera** [comment]
Al ser el valor unico, se añade como hidden.

**Comment by jesusMadrazoCabrera** [comment]
No es lo que dijo nuno el otro dia. Dijo que habia que el comportamiento era que populara los datos con lainformación que ya habia.
Lo vuelvo a abrir.

**Comment by SergioCarrilloEspejo** [comment]
Cierro Issues Jesus
