### ISSUE TITLE
Creacion y configuracion de IBM Cloud

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#22]

**Comment by SergioCarrilloEspejo** [comment]
https://git.eu-de.bluemix.net/scarrilloespejo/Repositorio-Carrefour
https://c4-portal-frontend.eu-de.mybluemix.net/Main
https://c4-portal-backend.eu-de.mybluemix.net/api/v1/docs/#
