### ISSUE TITLE
Eliminar "Lot" de lo que mostramos al usuario. 

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#28]
<img width="436" alt="image" src="https://user-images.githubusercontent.com/44262150/47309937-f5c8fa00-d635-11e8-9b03-e292a72ba958.png">

**Comment by jesusMadrazoCabrera** [comment]
Se almacena como Lot, se podria quitar el Lot una vez que se guarda, es mas eficaz que hacer el parseado de la info que se muestra.

**Comment by jesusMadrazoCabrera** [comment]
No entiendo. TE refieres a que en IFT lo eliminen?

**Comment by SergioCarrilloEspejo** [comment]
Quitado .Lot hardcodeado a mano
