### ISSUE TITLE
En Granja, al seleccionar un lote de busqueda, no recupera todos los datos

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#29]
No recupera todos los datos: falta granja, y nave.
<img width="881" alt="image" src="https://user-images.githubusercontent.com/44262150/47309999-2446d500-d636-11e8-91f6-a389fade6aca.png">

**Comment by jesusMadrazoCabrera** [comment]
Pte de Subir, recupera todo, excepto la nave

**Comment by jesusMadrazoCabrera** [comment]
Debe recuperar la nave también...

**Comment by jfmarquez** [comment]
Se ha corregido, carga los campos y rellena del payload la tabla
