### ISSUE TITLE
En matadero  no aparecen las salas de despiece cargadas

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#30]
en la pantalla de matadero no aparecen todas las salas de despiece cargadas.
Es un problema del tipo de facility? La sala de despiece se ha cargado en el excel como MINCER.

Aqui mas detalles: 
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/44262150/47310235-d1b9e880-d636-11e8-8d42-08b9e1ce5df7.png">

**Comment by jesusMadrazoCabrera** [comment]
MINCER????
Eso es un error de carga, o bien hay que modificar el codigo???

**Comment by jesusMadrazoCabrera** [comment]
Mira  en slack lo que dice Suneil ahora.. dice que hay que cambiar de Processing plant a Mincer ... no digo lo que pienso.. 
<img width="909" alt="image" src="https://user-images.githubusercontent.com/44262150/47312199-febcca00-d63b-11e8-9593-726711072bb8.png">

**Comment by SergioCarrilloEspejo** [comment]
![image](https://user-images.githubusercontent.com/44267161/47371324-df7b7680-d6e7-11e8-9885-dd36673671ca.png)
Si lo carga
