### ISSUE TITLE
pantalla Prep-Pedidos sale dos veces fecha prevista de entrega

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#31]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/44262150/47311012-fa42e200-d638-11e8-860d-c3d2366bdab7.png">

**Comment by jesusMadrazoCabrera** [comment]
Se cierra, adjunto pantallazo del cloud

![image](https://user-images.githubusercontent.com/44262150/47374773-fffaff00-d6ee-11e8-9fff-f86a48ffe398.png)

**Comment by SergioCarrilloEspejo** [comment]
Entiendo que esto a quedado solucionado con los arreglos del maquetador

![image](https://user-images.githubusercontent.com/44267161/47375112-cd053b00-d6ef-11e8-9b24-9301398d1ba7.png)
