### ISSUE TITLE
Modificaciones diseño en pag. Cliente carrefour

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#36]
* En la página cliente en lugar de "Plataforma Distribución" debe salir "Plataforma Carrefour". Por debajo seguirá apareciendo el nombre de la plataforma tal y como está ahora:

![image](https://user-images.githubusercontent.com/44262150/47351704-d8893f80-d6b8-11e8-8121-825c22c63b8c.png)

* Por debajo del nombre de la plataforma, con la misma sangría y lettering en negrita, poner "EN TU TIENDA CARREFOUR"

**Comment by jesusMadrazoCabrera** [comment]
Nuno, debajo de la plataforma unicamente aparecerá "EN TU TIENDA CARREFOUR""
Hay alguna linea, algo que siga la traza?
El logo de C4 se mantiene donde eta ahora, o baja hasta el ultimo punto??

**Comment by jesusMadrazoCabrera** [comment]
Por no abrir otra, ok? si quieres, se abre una nueva... a gusto...

La fecha esta siendo recogida en pantalla como MM/DD/YYYY en vez de DD/MM/YYYY
![image](https://user-images.githubusercontent.com/44262150/47642736-b0db2100-db69-11e8-90da-b62ac3f79c7a.png)

La fecha de salida de granja, que es la fecha de entrada en matadero, no esta siendo recogida.
![image](https://user-images.githubusercontent.com/44262150/47642762-c3edf100-db69-11e8-94a6-349e0e7d1718.png)

**Comment by jesusMadrazoCabrera** [comment]
(Isra): @SergioCarrilloEspejo  

1. Revisa que el texto de CRIA, donde pone sistema de Cria:
.... minima de sacrificio de 56 día " (debe ser 56 días).
2. que permite recuperar la fecha en el apartado de Cria (actualmente aparece fecha no encontrada).

**Comment by SergioCarrilloEspejo** [comment]
Pendiente de cambios
