### ISSUE TITLE
Inserción campo fecha de entrega en Página de cliente 

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#38]
Hay que insertar el campo de fecha de entrega en plataforma (de la pantalla de prepacion de pedidos) en la pagina de cliente (este es un requisito nuevo de C4)... 
ojo que antes hay que valorar el esfuerzo en modificar esto!!

![image](https://user-images.githubusercontent.com/44262150/47355296-4f2a3b00-d6c1-11e8-88a5-d2418932afa2.png)

**Comment by jesusMadrazoCabrera** [comment]
tiene que ir asi: 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/44262150/47355877-dcba5a80-d6c2-11e8-90f8-c70c7f984180.png">

**Comment by SergioCarrilloEspejo** [comment]
Listo para evaluar

**Comment by jesusMadrazoCabrera** [comment]
Revisado (Israel)
