### ISSUE TITLE
INCUBADORA  - visualización documento

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#42]
Tipo Mayor: Se ha grabado un documento en incubadora.
 - se desconfigura la tabla donde se muestra el documento
 - el documento no se puede abrir desde la pantalla una vez guardado
 - sale mensaje de log después de haber dado a guardar.
 
![capturainc](https://user-images.githubusercontent.com/43852358/47422449-edcaa080-d782-11e8-86df-29793459a0f0.JPG)

**Comment by jesusMadrazoCabrera** [comment]
Confirmado que Incubadora desaparece
