### ISSUE TITLE
GRANJA - Buscar Lote

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#44]
Al buscar un lote de cría en la pantalla de Granja (que se ha grabado anteriormente con algunos datos, no su totalidad), el buscar este lote por la opción de búsqueda:

- no se recupera la granja, ni la nave, ni las estirpes para la que se grabó

**Comment by jesusMadrazoCabrera** [comment]
[JMC] Cierro por duplicidad con #12
