### ISSUE TITLE
Matadero - control de fechas

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#45]
En Matadero la fecha de sacrificio debe poder ser igual a la fecha de entrada en matadero. 

*TIP: alimentar por defecto la fecha de sacrificio con la fecha de entrada en granja

**Comment by jesusMadrazoCabrera** [comment]
Pte de subir al entorno, no se puede cerrar hasta entonces.
![image](https://user-images.githubusercontent.com/44262150/47522860-f2807900-d896-11e8-808c-70608251b869.png)

![image](https://user-images.githubusercontent.com/44262150/47522894-01ffc200-d897-11e8-8429-f1f1d8a8742d.png)

**Comment by jesusMadrazoCabrera** [comment]
Revisado (Israel)
