### ISSUE TITLE
Matadero - (TODAS) Al GUARDAR si faltan datos no sale ningun mensaje diciendo si se han guardado o no los datos.

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#46]
Al GUARDAR si faltan datos no sale ningun mensaje diciendo si se han guardado o no los datos.

Caso general: si se guardan los datos, al volver a introducir los códigos de lote, éstos deben recuperarse.

**Comment by jesusMadrazoCabrera** [comment]
Pte de Subir.
Se ha comprobado en Granja, Matadero, Despiece y Pedido

![image](https://user-images.githubusercontent.com/44262150/47523921-881d0800-d899-11e8-896f-5273d7c46a10.png)

**Comment by jesusMadrazoCabrera** [comment]
Tenemos que revisar esto juntos.

**Comment by jesusMadrazoCabrera** [comment]
Relacionado con los issue #61 y #63 .
Cuando cerremos una, el resto irá en bloque.
