### ISSUE TITLE
PREPARACIÓN PEDIDO - id planta procesado", que no estaba en el mockup debe cumplimentarse automáticamente 

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#49]
En la pantalla de preparación de pedido, el "id planta procesado", que no estaba en el mockup debe cumplimentarse automáticamente al informar el ID lote Despiece.

**Comment by jesusMadrazoCabrera** [comment]
(Israel): este issue lo cree yo hace 4 dias.

**Comment by amoranviewnext** [comment]
Ya aparece marcada por defecto la planta de procesado al entrar en Preparacion pedido

**Comment by jesusMadrazoCabrera** [comment]
Revisado (Israel)
