### ISSUE TITLE
En Prep Pedido el Clear no limpia todos los campos

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#50]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/44262150/47425507-d2fc2a00-d78a-11e8-946b-749e545da757.png">

**Comment by jfmarquez** [comment]
Se limpian todos excepto planta procesado (solo hay 1 y siempre aparecerá marcada)

**Comment by jesusMadrazoCabrera** [comment]
Revisado (Israel)
