### ISSUE TITLE
INCUBADORA: BÚSQUEDA INCUBADORA

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#54]
El botón de búsqueda en la pantalla de incubadora: intento buscar la incubadora "Centro Tecnológico de Incubación" y no lo busca.

Al pulsar una tecla o digitar una letra en el combo de búsqueda se abra una lista. No se entiende el critario de filtro que tiene. El scroll es inmanejable.

**Comment by jesusMadrazoCabrera** [comment]
Definir el criterio de funcionamiento.

**Comment by Nunomsspaixao** [comment]
La pantalla de búsqueda debe permitir buscar una incubadora, tecleando bien el nombre de la incubadora, sin distinción de mayúsculas, minúsculas, bien por el id incubadora.

**Comment by jesusMadrazoCabrera** [comment]
(Israel)
Este issue tiene varios puntos: 
1. No funciona la busqueda. Si le ponemos busqueda por un string (pej Centro) no muestra nada .. a pesar de que si seleccionas la incubadora, te aparece la lista de incubadoras.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/44262150/47445034-2d5faf80-d7b8-11e8-95b4-a8f5aece779b.png">

2. Al seleccionar una incubadora, en teoría debería de recuperar los documentos que están guardados... pero esto no es así... ya que al guardar un documento (he probado a guardar uno de cada tipo en formato jpeg) no los guarda.

**Comment by jesusMadrazoCabrera** [comment]
Cerramos por incubadora
