### ISSUE TITLE
GRANJA - CAMPO BÚSQUEDA

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#55]
El literal en el campo de búsqueda en Granja debe de ser "Buscar ID Lote Cría"  - coherencia con el campo que se está buscando. Actualmente se llama ID Lote Granja.

**Comment by jesusMadrazoCabrera** [comment]
Facil

**Comment by jesusMadrazoCabrera** [comment]
Revisado (Israel)
