### ISSUE TITLE
Granja, al buscar y seleccionr un lote de granja creado NO recupera la granja

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#56]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/44262150/47442648-f76bfc80-d7b2-11e8-9b77-696f472e8d83.png">

**Comment by SergioCarrilloEspejo** [comment]
![image](https://user-images.githubusercontent.com/44267161/47443347-5da54f00-d7b4-11e8-8d3f-0ffcd91b1345.png)
