### ISSUE TITLE
GRANJA - CONSULTA CERTIFICADOS

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#59]
No permite descargar/consultar los certificados grabados en la pantalla. El usuario debe poder abrir el documento al pulsar sobre el link del nombre del fichero.

**Comment by Nunomsspaixao** [comment]
He visto que sí descarga. Habría que dejar el nombre del fichero en subrayado o poner en azul para que sea identificable al usuario que es donde debe pulsar si lo quiere consultar.

**Comment by jesusMadrazoCabrera** [comment]
@JesusMadrazo : puedes mirar esto? creo que el cambio / actualiación es fácil

**Comment by jesusMadrazoCabrera** [comment]
Revisado (Israel)
