### ISSUE TITLE
Orden de la tabla de documentos

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#6]
En incubadora, en la tabla de abajo,que permita ordenar por fecha de subida y/o tipo de certificado (Diseñador) (En general en todas las tablas tienen que permitir ordenar por fecha y tipo de certificado)

**Comment by jesusMadrazoCabrera** [comment]
[Eq. Diseño]

**Comment by jesusMadrazoCabrera** [comment]
[Eq. Diseño]

**Comment by jesusMadrazoCabrera** [comment]
https://scotch.io/tutorials/sort-and-filter-a-table-using-angular

**Comment by jesusMadrazoCabrera** [comment]
Pendiente de probar en el entorno, hasta que no se suba no se puede cerrar.

**Comment by jfmarquez** [comment]
Ordenacion de tabla documentos probada en entorno.
