### ISSUE TITLE
GRANJA - TABLA CERTIFICADOS

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#60]
En la tabla de Granja igual que en incubadora, no deben aparecer los campos V/F y fecha de caducidad.

**Comment by jesusMadrazoCabrera** [comment]
Tienes razon... lo reviso y asigno a Juan Francisco (Israel)

**Comment by jfmarquez** [comment]
Se quitan los certificados fijos de Incubadora y Granja
