### ISSUE TITLE
MATADERO - Check Supervisión Bien Estar Animal

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#62]
En la pantalla de Matadero Falta el Check de Bienestar Animal. Según especificado en las validaciones de Mock-up del 04/09:

MODIFICACIONES 04/09

Es necesario incluir en la pantalla matadero un check Y/N (Supervisión Bienestar Animal). 
Para aquellos ID Lote Matadero que no tengan marcado este campo con “Y” no se podrán seleccionar en el paso siguiente. Es decir al crear un “ID Lote Despiece”, no aparecerán como disponibles lotes “ID Lote Matadero” que no tengan informado el campo “Supervisión Bienestar Animal” a Y

**Comment by jesusMadrazoCabrera** [comment]
Perdona Juanfra, al final era en matadero.

**Comment by jfmarquez** [comment]
Probado en entorno guarda valor y se recupera del valor del lote. La validacion para despiece habrá que hacerla en la carga de despiece.
