### ISSUE TITLE
MATADERO - BÚSQUEDA ID LOTE MATADERO

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#64]
He registrado el lote id matadero: NUNO2MAT, 
![image](https://user-images.githubusercontent.com/43852358/47482275-5f175b80-d836-11e8-811a-95a8fd3b40e9.png). Se ha pulsado el botón "CLEAR" e intentado buscar en el combo de selección el ID Lote Matadero con "NUNO2MAT" no obstante no se muestran resultados:
![image](https://user-images.githubusercontent.com/43852358/47482356-9c7be900-d836-11e8-8365-5162f9e6207a.png)

**Comment by jesusMadrazoCabrera** [comment]
A revisar por angel y jesus (creo que ya está corregido en la nueva versión).

**Comment by jesusMadrazoCabrera** [comment]
No esta corregido, de cara a las busquedas, hay que recargar la pagina.
No es una incidencia.

**Comment by jesusMadrazoCabrera** [comment]
Revisado (Israel)
