### ISSUE TITLE
0 - MATADERO - REGISTRAR UN ID LOTE YA EXISTENTE

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#65]
Es necesario que si se introduce un código de lote id matadero que ya se haya creado previamente, se muestre un mensaje informando: "Ya existen datos para el lote xxxx. Desea recuperar los datos guardados anteriormente?"

Si el usuario contesta "Sí", se recuperarán los datos guardados para ese lote anteriormente, (certificados incluídos). El usuario podrá modificar los datos (respetando las validaciones que se efectuan sobre el periodo de estancia en granja).

Si el usuario contesta NO se blanqueará la pantalla, incluido el campo código Lote que acaba de introducir.

**Comment by jesusMadrazoCabrera** [comment]
@Nunomsspaixao , una duda, con esto, si tenemos un componente de búsqueda arriba y realmente, usamos un componente de búsqueda abajo, igual, con el mismo tipo de  búsqueda (Lotes) considerais  realmente necesario el componente de búsqueda???

**Comment by Nunomsspaixao** [comment]
La validación al introducir el codigo de lote, es necesaria ya que de otro, el usuario puede incurrir en errores. Respecto a la búsqueda en la parte superior, la idea es que esta evolucione (buscar por fechas, etc.).

**Comment by jesusMadrazoCabrera** [comment]
Ok, estamos implementando la solución, para poder ponerla a vuestra disposición lo antes posible

**Comment by jesusMadrazoCabrera** [comment]
Parece que te bloquea si alguno coincide.
Quiero decir, si quieres meter como lote 123456 y existe un lote 12345, no te da la opción de poder seguir incluyendo.
Modificar la validación, para que se produzca cuando se realice un evento onBlur del campo con el valor definitivo.
