### ISSUE TITLE
Cambios Frontal, eliminación campos V/F - Fecha caducidad y adecuación tabla

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#66]
Descripción el problema:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/44262150/47497837-a6fca980-d85b-11e8-95fd-ed2d5450ea7a.png">

Solución: Hay que seguir lo que indica Carlos gonzalez

<img width="601" alt="image" src="https://user-images.githubusercontent.com/44262150/47497888-cd224980-d85b-11e8-9f25-cc424fbdfb19.png">

**Comment by jfmarquez** [comment]
Comprobado en development
