### ISSUE TITLE
MATADERO - NO GUARDA LOTE

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#70]
![image](https://user-images.githubusercontent.com/43852358/47512394-64979480-d87c-11e8-92bd-27d853801912.png)

He creado un lote Matadero (pantallazo arriba), aparece como guardado, no obstante:

- iba un documento adjunto que no aparece en la lista de documentos
- al buscar el lote creado este no aparece en lista en la búsqueda:

![image](https://user-images.githubusercontent.com/43852358/47512542-b6d8b580-d87c-11e8-9e55-62275b3dfc65.png)

**Comment by jesusMadrazoCabrera** [comment]
Revisar por parte de Jesus.

**Comment by Nunomsspaixao** [comment]
Has probado guardar un lote, subiendo el documento antes de darle a guardar? No tengo disponible el entorno no puedo volver a probar.

**Comment by jesusMadrazoCabrera** [comment]
El problema viene generado por cómo se está gestionando los documentos.
Hemos abierto otra issue para solventarlo.

**Comment by jfmarquez** [comment]
Esta issue se solucionará con el proximo despliegue, al crear un lote con documento, antes, creaba el payload con el documento pero no creaba el lote. Ahora ya lo hace correctamente
