### ISSUE TITLE
MATADERO - BÚSQUEDA LOTE MATADERO

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#71]
Al buscar un lote matadero:

![image](https://user-images.githubusercontent.com/43852358/47513369-62ced080-d87e-11e8-8f00-d272b4412acc.png)

No se  muestra: 

- Lote de Cría
- Matadero
- Sala Despiece 

con los que se han registrado el lote.

**Comment by jesusMadrazoCabrera** [comment]
Cerrado. Comprobado que funciona (Israel)
