### ISSUE TITLE
0-MATADERO - SE GUARDA CERTIFICADO AUNQUE NO SE PULSE GUARDAR

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#72]
He probado crear un lote Matadero. Posteriormente busqué el lote (NUNO100M2) para añadir un certificado. Después de haber elegido el documento no he pulsado guardar. Vuelvo a repetir la operación y la segunda vez si se pulsa guardar. Al buscar el lote, este documento aparece registrado dos veces (la primera vez aunque no se pulsó guardar sí se guardó):

![image](https://user-images.githubusercontent.com/43852358/47515339-e4c0f880-d882-11e8-8241-0b47cd0afa04.png)

**Comment by jesusMadrazoCabrera** [comment]
[JMC] Nuno, realmente, como nunca se definió por ninguna de las partes, se ha generado un evento que sube documentos cuando cambias el valor del campo "SELECCIONAR ARCHIVO"

Podemos incluir un alert, indicando que se va a proceder a subir el archivo (Te parece bien?)

**Comment by Nunomsspaixao** [comment]
La cuestión es que si el usuario está cumplimentado datos y finalmente no pulsa el botón guardar, éstos no deberían guardarse. No me quiero meter con que si se definió o no, pero me parece lógico en cualquier pantalla, formulario de datos, que si no confirmas que quieres guardar, registrar, etc, que éstos no se guarden. 

Si no has informado lote y  has subido un documento y no guardas, ¿éste se sube igual? Es que si te equivocas de fichero, cancelas el registro al volver a intentar crear ese lote te va a aparecer ese fichero.

**Comment by jesusMadrazoCabrera** [comment]
Se cierra por petición #76, que describe un comportamiento global y no especifico para 1 pantalla
