### ISSUE TITLE
Readaptar el flujo de los ficheros y los lotes

### ISSUE THREAD

**Issue by jesusMadrazoCabrera** [jesusMadrazoCabrera/C4-Portal-Back#76]
Hay que cambiar el flujo para la carga de ficheros.
Permitir la carga de 1 o varios ficheros a la vez.
No cargarlos hasta que se pulse el botón de guardar.

**Comment by jesusMadrazoCabrera** [comment]
Si, aqui incluso quizas seria mas facil que abriera un pop-up, que salga el cuadro, que permita ir seleccionado ficheros, y que al pulsar en el guardar del pop.up los guardara en BDS y añadiera el codigo en la pantalla correspondiente (que pasaria si al final el usuario no guarda el lote?? los documentos se quedarian guardados??)

**Comment by jesusMadrazoCabrera** [comment]
Ahora mismo si, por eso es esta issue, para evitar ese comportamiento

**Comment by jesusMadrazoCabrera** [comment]
Probando en varias ocasiones, me encuentro un comportamiento extraño, identifico paso a paso el funcionamiento deseado.

Al crear un  lote, y seleccionar un fichero, 
Como hasta ahora se debe crear una  linea en la tabla de documentos, con el documento a subir.
Habilitar la posibilidad de subida multiple, pudiendo subir 1 o n documentos cuando pulse a guardar.
Cada vez que el usuario intente añadir un fichero, se sumara una linea con los datos.
No se subirán los documentos a BDS hasta que el usuario pulse en guardar.

Al recuperar un lote, en el nombre, debe dar la opción de descargar el fichero.
El nombre debe estar resaltado en azul, subrayado y con el puntero como si fuera una descarga, no con la flecha.
En la consulta/modificacion del lote, debemos permitir añadir ficheros, tambien, con la opcion multiple, añadiendo una linea a la lista y con el mismo comoprtamiento que el alta (Solo debemos subir los nuevos documentos, no tocar los que ya esten asociados al lote.)

**Comment by jfmarquez** [comment]
Se ha modificado el flujo de fichero para que se puedan ir añadiendo mas de un fichero a un lote. Aparecerán botones de "Delete" junto a los ficheros por si se desea eliminar antes de la subida. Una vez guradados, el boton desaparece. Cuando se carga el lote creado, aparecen los ficheros subidos para ese lote.

**Comment by jfmarquez** [comment]
Realizados cambios que no dejaban guardar lotes.
