### ISSUE TITLE
GRANJA - CAMPO CANTIDAD SIN VALIDAR FORMATO

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#82]
El campo cantidad permite introducir símbolos ("."; "-") esto puede llevar a errores del usuario. Al ser un campo número debería validar ese formato:

![image](https://user-images.githubusercontent.com/43852358/47615458-45347d80-daaf-11e8-88ca-358e66e80390.png)

**Comment by jesusMadrazoCabrera** [comment]
@Nunomsspaixao , dejaremos la posibilidad de meter . y , por el tema de los templates, el resto de caracteres no numericos los bloquearemos, ok?

**Comment by Nunomsspaixao** [comment]
Pero el . y , cómo lo integra en IFT?

**Comment by jfmarquez** [comment]
Validacion de campos cantidad hecha
