### ISSUE TITLE
PREPARACIÓN PEDIDO - GUARDAR DATOS PEDIDO

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#85]
Todos los datos están cumplimentados, no obstante sale mensaje indicando que faltan datos:

![image](https://user-images.githubusercontent.com/43852358/47656077-a8e1a800-db8e-11e8-918d-81ebef5e3eb0.png)

Esto occure, si se utiliza el botón clear en lugar de refrescar y volver a entrar a la pantalla.

**Comment by jesusMadrazoCabrera** [comment]
@SergioCarrilloEspejo :  esto funciona mal ya que lo que ocurre es:
1. al darle a clear, borra todos los campos (esto está casi bien), incluidos los de planta procesado 
2. aparece como marcado Planta Procesado, pero realmente el campo o los campos (id planta procesado y localización) no captura el valor (es decir habria que llamar otra vez a la carga del form... 
3. esto lo podeis probar vosotros... si despues del clear vuelves a seleccionar la planta de procesado, funciona bien.. pero si no la seleccionas (auqnue aparece seleccionada) no deja grabar (ese es del dato que falta).

.. Solución: se podria llamar, cuando presionas clear.. a que recargue la pagina como si vinieramos desde matadero (pej)? entiendo que cuando se recarga la pagina, se limpian todos los form, y se marca por defecto la planta de procesado.
