### ISSUE TITLE
PÁGINA CLIENTE - COHERENCIA FORMATO FECHAS

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#86]
Revisar el formato de fechas en la página cliente. Todas las fechas deben ser DDMMAAAA

![image](https://user-images.githubusercontent.com/43852358/47657530-8c933a80-db91-11e8-9e96-f8574d120592.png)

**Comment by jesusMadrazoCabrera** [comment]
@SergioCarrilloEspejo 
en el campo de url estamos pasando el formato dd/mm/YYYY
pero en la app estamos mostrado en formato americano: mm/dd/yyyy

deberiamos de comprobar que en todos los campos fecha que esta en formato europeo (dd/mm/yyyy)
