### ISSUE TITLE
PAGINA CLIENTE - DATO NO DISPONIBLE

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#88]
¿En qué casos se abre la página de error? Meti un lote inválido y se muestra la página normal diciendo "dato no disponible":

![image](https://user-images.githubusercontent.com/43852358/47745999-50d99d00-dc85-11e8-921e-c391764729a7.png)

**Comment by jesusMadrazoCabrera** [comment]
@Nunomsspaixao 
Cualquiera que tenga un parametros similar a estos.
https://pollocalidadyorigen-dev.carrefour.es/search?lote=123123123&fecha=10-10-10

**Comment by Nunomsspaixao** [comment]
@JesusMadrazo en la URL de mi ejemplo el lote No existe en IFT. No debería abrir la página de error? Es decir:

- qué ocurre si el lote no existe?
- qué ocurre si el lote existe pero no existen otros datos en IFT?

**Comment by jesusMadrazoCabrera** [comment]
@Nunomsspaixao defineme el comportamiento deseado para cada uno de los puntos..

Que es lo que debe hacer todos ellos?

**Comment by Nunomsspaixao** [comment]
En ambos casos si la URL es correcta pero ni existen datos (alguno de los datos), ni los parametros informados son correctos debe mostrarse la página de contingencia, siempre que la raíz de la url sea la de pollo calidad y origen.
