### ISSUE TITLE
BOTON CLEAR

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#89]
Después de haber guardado un lote, utilizando el botón clear para borrar datos y crear uno nuevo, el combo granja deja de funcionar. 

![image](https://user-images.githubusercontent.com/43852358/47806192-6ad4b780-dd39-11e8-82e1-65879a705f05.png)

**Comment by jesusMadrazoCabrera** [comment]
@Nunomsspaixao resuelto y subido, ten en cuenta que estamos haciendo mil despliegues en estos momentos.
