### ISSUE TITLE
TABLA DOCUMENTOS - DESCONFIG

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#91]
Verificar la configuración de la tabla de documentos anexos: 

![image](https://user-images.githubusercontent.com/43852358/47848040-53dfa500-ddcd-11e8-87f9-6230e55db1d4.png)

**Comment by SergioCarrilloEspejo** [comment]
@Nunomsspaixao Hola, puedes explicarme a que te refieres ? Estoy mirandolo y no entiendo a que te refieres.
Dimelo para poder continuar con estas cosas.

**Comment by Nunomsspaixao** [comment]
Hola, me refiere a que la tabla no sale correctamente configurada - a al derecha se pierde el borde:

![image](https://user-images.githubusercontent.com/43852358/47912269-54913d80-de98-11e8-93cd-d637142177bf.png)

**Comment by Nunomsspaixao** [comment]
Pasa en Granja.

**Comment by SergioCarrilloEspejo** [comment]
He solucionado la tabla el borde, al mismo tiempo he quitado el boton de Delete y puesto una papelera de reciclaje ( es de Icon-Icon y es freeware podeis estar tranquilo por la licencia. @Nunomsspaixao @JesusMadrazo Adjunto los pantallazos y no tengais en cuenta lo mal que bordeo con el amarillo ;)
![solucionado pantalla](https://user-images.githubusercontent.com/44267161/47913722-6b865e80-de9d-11e8-8311-eb871d55b777.PNG)
