### ISSUE TITLE
MATADERO - RECUPERAR DATOS

### ISSUE THREAD

**Issue by Nunomsspaixao** [jesusMadrazoCabrera/C4-Portal-Back#94]
Al introducir el código de lote (en el formulario) y al recuperar los datos no se muestra 1 de los 3 adjuntos:

![image](https://user-images.githubusercontent.com/43852358/47849496-29441b00-ddd2-11e8-8c00-6ea5a0d889a7.png)

**Comment by SergioCarrilloEspejo** [comment]
He comprobado con la versión que esta subida en Bluemix y en Matadero ese error no me lo ha dado,

La unica explicación que le veo es que esta prueba no esperara a que terminaran de cargarse los ficheros, o que por algun motivo del Cloud no haya cargado correctamente en su momento.
![prueba matadero](https://user-images.githubusercontent.com/44267161/47910285-a33bd900-de92-11e8-90e6-db60136bd459.PNG)

**Comment by Nunomsspaixao** [comment]
Ok al cierre, pero seguro está relacionado con la 94# - el poder grabar habiendo eligiendo un tipo de certificado sin adjuntar documento genera el registro vacío.
